---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: delegated
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: local
platforms:
  - name: localhost
    groups:
      - local_molecule
      - ${IVATEST_PYTHON_GROUP:-python_autodetect}
provisioner:
  name: ansible
  inventory:
    links:
      hosts: $MOLECULE_SCENARIO_DIRECTORY/../default/hosts.yml
  playbooks:
    prepare: $MOLECULE_SCENARIO_DIRECTORY/../default/playbooks/${PLAYBOOK:-starter}-init.yml
    converge: $MOLECULE_SCENARIO_DIRECTORY/../default/playbooks/${PLAYBOOK:-starter}-play.yml
    verify: $MOLECULE_SCENARIO_DIRECTORY/../default/playbooks/${PLAYBOOK:-starter}-test.yml
  env:
    ANSIBLE_ROLES_PATH: $MOLECULE_PROJECT_DIRECTORY/roles:$MOLECULE_PROJECT_DIRECTORY/roles-galaxy:$MOLECULE_PROJECT_DIRECTORY/roles-temp
    ANSIBLE_CALLBACK_PLUGINS: $MOLECULE_PROJECT_DIRECTORY/plugins/callback
    ANSIBLE_STRATEGY_PLUGINS: $MOLECULE_PROJECT_DIRECTORY/plugins/strategy/mitogen
  config_options:
    defaults:
      strategy: mitogen_linear
      stdout_callback: unixy2
      verbosity: 1
  lint:
    name: ansible-lint
verifier:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  test_sequence:
    - lint
    - dependency
    - syntax
    - prepare
    - converge
    - idempotence
    - verify
  create_sequence:
    - create
    - prepare
  destroy_sequence:
    - cleanup
    - destroy
  converge_sequence:
    - converge
...
