---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
platforms:
  - name: xenial
    groups:
      - docker_molecule
    image: ivandeex/molecule:16.04
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
  - name: bionic
    groups:
      - docker_molecule
    image: ivandeex/molecule:18.04
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    links:
      hosts: ../default/hosts.yml
      group_vars: ../../inventory/group_vars
      host_vars: ../../inventory/host_vars
  playbooks:
    prepare: ../default/playbooks/${PLAYBOOK:-starter}-init.yml
    converge: ../default/playbooks/${PLAYBOOK:-starter}-play.yml
    verify: ../default/playbooks/${PLAYBOOK:-starter}-test.yml
  env:
    ANSIBLE_ROLES_PATH: ../../roles:../../roles-galaxy:../../roles-temp
    ANSIBLE_CALLBACK_PLUGINS: ../../plugins/callback
  config_options:
    defaults:
      stdout_callback: unixy2
  lint:
    name: ansible-lint
verifier:
  name: ansible
  lint:
    name: ansible-lint
lint:
  name: yamllint
  options:
    config-file: .yamllint.yml
scenario:
  test_sequence:
    - lint
    - dependency
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - verify
    - destroy
  create_sequence:
    - create
    - prepare
  destroy_sequence:
    - cleanup
    - destroy
  converge_sequence:
    - converge
...
