---
branches:
  only:
    - master
    - /^v/
language: python
python: 3.6
os: linux

# job matrix
jobs:
  include:
    ###### plugins
    - name: plugins
      env: TARGET=plugins
      services: docker
      dist: bionic
    ###### bastion
    ### (bastion is flagged - testing isolated in docker)
    # - name: bastion local xenial
    #   env: PLAYBOOK=bastion TARGET=local
    #   dist: xenial
    # - name: bastion local bionic
    #   env: PLAYBOOK=bastion TARGET=local
    #   dist: bionic
    - name: bastion docker xenial
      env: PLAYBOOK=bastion TARGET=xenial
      services: docker
      dist: bionic
    - name: bastion docker bionic
      env: PLAYBOOK=bastion TARGET=bionic
      services: docker
      dist: bionic
    ####### master
    ### (master is flagged - testing isolated in docker)
    # - name: master local xenial
    #   env: PLAYBOOK=master TARGET=local
    #   dist: xenial
    # - name: master local bionic
    #   env: PLAYBOOK=master TARGET=local
    #   dist: bionic
    - name: master docker xenial
      env: PLAYBOOK=master TARGET=xenial
      services: docker
      dist: bionic
    - name: master docker bionic
      env: PLAYBOOK=master TARGET=bionic
      services: docker
      dist: bionic
    ####### devops
    - name: devops local xenial
      env: PLAYBOOK=devops TARGET=local
      dist: xenial
    - name: devops local bionic
      env: PLAYBOOK=devops TARGET=local
      dist: bionic
    # - name: devops docker xenial
    #   env: PLAYBOOK=devops TARGET=xenial
    #   services: docker
    #   dist: bionic
    # - name: devops docker bionic
    #   env: PLAYBOOK=devops TARGET=bionic
    #   services: docker
    #   dist: bionic
    ####### ivantory
    - name: ivantory local xenial
      env: PLAYBOOK=ivantory TARGET=local
      dist: xenial
    - name: ivantory local bionic
      env: PLAYBOOK=ivantory TARGET=local
      dist: bionic
#   - name: ivantory docker xenial
#     env: PLAYBOOK=ivantory TARGET=xenial
#     services: docker
#     dist: bionic
#   - name: ivantory docker bionic
#     env: PLAYBOOK=ivantory TARGET=bionic
#     services: docker
#     dist: bionic
####### starter
### (starter mainly duplicates ivantory - disabled)
#   - name: starter local xenial
#     env: PLAYBOOK=starter TARGET=local
#     dist: xenial
#   - name: starter local bionic
#     env: PLAYBOOK=starter TARGET=local
#     dist: bionic
#   - name: starter docker xenial
#     env: PLAYBOOK=starter TARGET=xenial
#     services: docker
#     dist: bionic
#   - name: starter docker bionic
#     env: PLAYBOOK=starter TARGET=bionic
#     services: docker
#     dist: bionic
# end of matrix

# stages
install:
  - pip3 install -U pip setuptools wheel
  # also pulled: ansible-lint yamllint flake8
  - pip3 install docker jmespath mitogen molecule pytest testinfra
  # fix mitogen strategy symlink
  - ln -sf $(python3 -c "import ansible_mitogen; print(ansible_mitogen.__path__[0])")/plugins/strategy ./plugins/strategy/mitogen
  # fix symlink for a role with custom modules
  - ln -sf ~/.cache/molecule/ivantory-test/$TARGET/roles ./roles-galaxy

before_script: |
    # fix issues with postgresql install on travis
    case "$PLAYBOOK.$TARGET" in
      master.local )
        sudo apt-get -qy purge \
             postgresql-common postgresql-client-common \
             postgresql-10-postgis-2.4-scripts \
             postgresql-9.4-postgis-2.4-scripts postgresql-9.5-postgis-2.4-scripts postgresql-9.6-postgis-2.4-scripts
        sudo rm -rf /var/lib/postgresql
        ;;
    esac
    # per-target adjustments
    case "$TARGET" in
      local )
        export IVATEST_FIREWALL=ferm
        export IVATEST_SSH_SERVER=true
        export IVATEST_SYSTEMD_TMPFILES=true
        ;;
      xenial | bionic )
        export IVATEST_FIREWALL=none
        export IVATEST_SSH_SERVER=true
        export IVATEST_SYSTEMD_TMPFILES=true
        ;;
    esac

script:
  - molecule test -s $TARGET
...
