---
collections:
  - git+https://github.com/ivansible/asterisk
  - git+https://github.com/ivansible/base
  - git+https://github.com/ivansible/cert
  - git+https://github.com/ivansible/devel
  - git+https://github.com/ivansible/entware
  - git+https://github.com/ivansible/linux
  - git+https://github.com/ivansible/ndms
  - git+https://github.com/ivansible/nginx
  - git+https://github.com/ivansible/server
  - git+https://github.com/ivansible/termux
  - git+https://github.com/ivansible/vagrant
...
