---
# - src: https://github.com/ivansible/vansible1
#  name: ivansible.vansible1
#  version: multi
#  scm: git
- src: https://github.com/ivansible/lin-base
  name: ivansible.lin_base
  scm: git
- src: https://github.com/ivansible/lin-enter
  name: ivansible.lin_enter
  scm: git
- src: https://github.com/ivansible/lin-core
  name: ivansible.lin_core
  scm: git
- src: https://github.com/ivansible/lin-ferm
  name: ivansible.lin_ferm
  scm: git
- src: https://github.com/ivansible/lin-ssh
  name: ivansible.lin_ssh
  scm: git
- src: https://github.com/ivansible/lin-motd
  name: ivansible.lin_motd
  scm: git
- src: https://github.com/ivansible/dev-user
  name: ivansible.dev_user
  scm: git
- src: https://github.com/ivansible/lin-refresh
  name: ivansible.lin_refresh
  scm: git
- src: https://github.com/ivansible/lin-ansible
  name: ivansible.lin_ansible
  scm: git
- src: https://github.com/ivansible/lin-docker
  name: ivansible.lin_docker
  scm: git
- src: https://github.com/ivansible/lin-podman
  name: ivansible.lin_podman
  scm: git
- src: https://github.com/ivansible/lin-rclone
  name: ivansible.lin_rclone
  scm: git
- src: https://github.com/ivansible/lin-restic
  name: ivansible.lin_restic
  scm: git
- src: https://github.com/ivansible/dev-jupyter
  name: ivansible.dev_jupyter
  scm: git
- src: https://github.com/ivansible/lin-devel
  name: ivansible.lin_devel
  scm: git
- src: https://github.com/ivansible/lin-go
  name: ivansible.lin_go
  scm: git
- src: https://github.com/ivansible/dev-ansible
  name: ivansible.dev_ansible
  scm: git
- src: https://github.com/ivansible/dev-ivantory
  name: ivansible.dev_ivantory
  scm: git
- src: https://github.com/ivansible/lin-nxserver
  name: ivansible.lin_nxserver
  scm: git
- src: https://github.com/ivansible/lin-virtualbox
  name: ivansible.lin_virtualbox
  scm: git
- src: https://github.com/ivansible/dev-vagrant
  name: ivansible.dev_vagrant
  scm: git
- src: https://github.com/ivansible/dev-hosters
  name: ivansible.dev_hosters
  scm: git
- src: https://github.com/ivansible/dev-terraform
  name: ivansible.dev_terraform
  scm: git
- src: https://github.com/ivansible/dev-packer
  name: ivansible.dev_packer
  scm: git
- src: https://github.com/ivansible/new-vultr
  name: ivansible.new_vultr
  scm: git
- src: https://github.com/ivansible/srv-mtproxy
  name: ivansible.srv_mtproxy
  scm: git
- src: https://github.com/ivansible/srv-dante
  name: ivansible.srv_dante
  scm: git
- src: https://github.com/ivansible/srv-cdn
  name: ivansible.srv_cdn
  scm: git
- src: https://github.com/ivansible/srv-ss
  name: ivansible.srv_ss
  scm: git
- src: https://github.com/ivansible/srv-chisel
  name: ivansible.srv_chisel
  scm: git
- src: https://github.com/ivansible/srv-doh
  name: ivansible.srv_doh
  scm: git
- src: https://github.com/ivansible/lin-tor
  name: ivansible.lin_tor
  scm: git
- src: https://github.com/ivansible/srv-ziproxy
  name: ivansible.srv_ziproxy
  scm: git
- src: https://github.com/ivansible/srv-squid
  name: ivansible.srv_squid
  scm: git
- src: https://github.com/ivansible/cert-base
  name: ivansible.cert_base
  scm: git
- src: https://github.com/ivansible/cert-cloudflare
  name: ivansible.cert_cloudflare
  scm: git
- src: https://github.com/ivansible/cert-master
  name: ivansible.cert_master
  scm: git
- src: https://github.com/ivansible/cert-replica
  name: ivansible.cert_replica
  scm: git
- src: https://github.com/ivansible/cert-copy
  name: ivansible.cert_copy
  scm: git
- src: https://github.com/ivansible/nginx-base
  name: ivansible.nginx_base
  scm: git
- src: https://github.com/ivansible/lin-sslh
  name: ivansible.lin_sslh
  scm: git
- src: https://github.com/ivansible/lin-nginx
  name: ivansible.lin_nginx
  scm: git
- src: https://github.com/ivansible/lin-uwsgi
  name: ivansible.lin_uwsgi
  scm: git
- src: https://github.com/ivansible/srv-postgres
  name: ivansible.srv_postgres
  scm: git
- src: https://github.com/ivansible/backup-base
  name: ivansible.backup_base
  scm: git
- src: https://github.com/ivansible/db-base
  name: ivansible.db_base
  scm: git
- src: https://github.com/ivansible/ast-base
  name: ivansible.ast_base
  scm: git
- src: https://github.com/ivansible/ast-core
  name: ivansible.ast_core
  scm: git
- src: https://github.com/ivansible/ast-soho
  name: ivansible.ast_soho
  scm: git
- src: https://github.com/ivansible/ast-providers
  name: ivansible.ast_providers
  scm: git
- src: https://github.com/ivansible/ast-webui
  name: ivansible.ast_webui
  scm: git
- src: https://github.com/ivansible/ast-billing
  name: ivansible.ast_billing
  scm: git
- src: https://github.com/ivansible/srv-cgpro
  name: ivansible.srv_cgpro
  scm: git
- src: https://github.com/ivansible/srv-mongodb
  name: ivansible.srv_mongodb
  scm: git
- src: https://github.com/ivansible/srv-redis
  name: ivansible.srv_redis
  scm: git
- src: https://github.com/ivansible/lin-rsyslog
  name: ivansible.lin_rsyslog
  scm: git
- src: https://github.com/ivansible/vag-ipv6dns
  name: ivansible.vag_ipv6dns
  scm: git
- src: https://github.com/ivansible/vag-share
  name: ivansible.vag_share
  scm: git
- src: https://github.com/ivansible/vag-vbguest
  name: ivansible.vag_vbguest
- src: https://github.com/ivansible/dns-cloudflare
  name: ivansible.dns_cloudflare
  scm: git
- src: https://github.com/ivansible/lin-bastion
  name: ivansible.lin_bastion
  scm: git
- src: https://github.com/ivansible/lin-net
  name: ivansible.lin_net
  scm: git
- src: https://github.com/ivansible/lin-wireguard
  name: ivansible.lin_wireguard
  scm: git
- src: https://github.com/ivansible/lin-yggdrasil
  name: ivansible.lin_yggdrasil
  scm: git
- src: https://github.com/ivansible/lin-keepalived
  name: ivansible.lin_keepalived
  scm: git
- src: https://github.com/ivansible/ndm-firewall
  name: ivansible.ndm_firewall
  scm: git
- src: https://github.com/ivansible/ndm-openvpn
  name: ivansible.ndm_openvpn
  scm: git
- src: https://github.com/ivansible/ndm-wireguard
  name: ivansible.ndm_wireguard
  scm: git
- src: https://github.com/ivansible/srv-dyndns
  name: ivansible.srv_dyndns
  scm: git
- src: https://github.com/ivansible/srv-openvpn
  name: ivansible.srv_openvpn
  scm: git
- src: https://github.com/ivansible/srv-sshtun
  name: ivansible.srv_sshtun
  scm: git
- src: https://github.com/ivansible/srv-v2ray
  name: ivansible.srv_v2ray
  scm: git
- src: https://github.com/ivansible/wrt-core
  name: ivansible.wrt_core
  scm: git
- src: https://github.com/ivansible/wrt-net
  name: ivansible.wrt_net
  scm: git
- src: https://github.com/ivansible/wrt-openvpn
  name: ivansible.wrt_openvpn
  scm: git
- src: https://github.com/ivansible/wrt-privoxy
  name: ivansible.wrt_privoxy
  scm: git
- src: https://github.com/ivansible/wrt-srelay
  name: ivansible.wrt_srelay
  scm: git
- src: https://github.com/ivansible/wrt-ss
  name: ivansible.wrt_ss
  scm: git
- src: https://github.com/ivansible/wrt-sshtun
  name: ivansible.wrt_sshtun
  scm: git
- src: https://github.com/ivansible/wrt-supervisor
  name: ivansible.wrt_supervisor
  scm: git
- src: https://github.com/ivansible/wrt-v2ray
  name: ivansible.wrt_v2ray
  scm: git
- src: https://github.com/ivansible/wrt-wireguard
  name: ivansible.wrt_wireguard
  scm: git
- src: https://github.com/ivansible/wrt-yggdrasil
  name: ivansible.wrt_yggdrasil
  scm: git
- src: https://github.com/ivansible/dev-nomad
  name: ivansible.dev_nomad
  scm: git
- src: https://github.com/ivansible/srv-netdata
  name: ivansible.srv_netdata
  scm: git
- src: https://github.com/ivansible/termux-bootstrap
  name: ivansible.termux_bootstrap
  scm: git
- src: https://github.com/ivansible/termux-core
  name: ivansible.termux_core
  scm: git
- src: https://github.com/ivansible/termux-ubuntu
  name: ivansible.termux_ubuntu
  scm: git
...
