---
all:
  children:
    # enabled groups
    molecule:
      children:
        docker_molecule:
        local_molecule:
    permitted:
      children:
        molecule:
    prod_all:
      children:
        prod_master:
          children:
            molecule:
        prod_slaves:
        prod_test:
    prod_master_all:
      children:
        prod_master:
    prod_slaves_all:
      children:
        prod_slaves:
    prod_core:
      children:
        prod_master:
        prod_slaves:
    asterisk_servers:
      children:
        molecule:
    # disabled groups
    dev_all:
      children:
        dev_master:
        dev_slaves:
    vagrant:
    baremetal:
    # hosts to skip, represented as groups
    bender:
...
