---
provisioner:
  name: ansible
  inventory:
    links:
      hosts: settings.yml
  playbooks:
    prepare: ${PLAYBOOK:-starter}/prepare.yml
    converge: ${PLAYBOOK:-starter}/converge.yml
    verify: ${PLAYBOOK:-starter}/verify.yml
  env:
    ANSIBLE_CALLBACK_PLUGINS: $MOLECULE_PROJECT_DIRECTORY/plugins/callback
    ANSIBLE_STRATEGY_PLUGINS: $MOLECULE_PROJECT_DIRECTORY/plugins/strategy/mitogen
    ANSIBLE_COLLECTIONS_PATH: $MOLECULE_PROJECT_DIRECTORY/collections
    ANSIBLE_ROLES_PATH: $MOLECULE_PROJECT_DIRECTORY/roles
  config_options:
    defaults:
      strategy: ${ANSIBLE_STRATEGY:-mitogen_linear}
      stdout_callback: ${ANSIBLE_STDOUT_CALLBACK:-unixy2}
      verbosity: 1
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
lint: |
  ansible-lint
scenario:
  test_sequence:
    # dependency
    - syntax
    - lint
    - destroy
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
  create_sequence:
    - create
    # prepare
  destroy_sequence:
    - destroy
    # cleanup
  converge_sequence:
    - converge
verifier:
  name: ansible
driver:
  name: docker
platforms:
  - name: focal.$PLAYBOOK
    groups:
      - docker_molecule
    image: ivandeex/molecule:20.04
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
...
