---
terraform_version: "0.12.13"

terraform_allow_reinstall_plugins: yes
terraform_provisioner_ansible_repo_owner: ivandeex
terraform_provisioner_ansible_version: 2.2.1-iva03
terraform_provisioner_ansible_is_tarball: true
terraform_provider_vultr_repo_owner: ivandeex
terraform_provider_vultr_version: 0.1.9-iva01

terraform_plans_repo: ""

terraform_api_token: ""
...
