---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
platforms:
  - name: focal
    groups:
      - docker_molecule
    image: ivandeex/molecule:20.04
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    links:
      hosts: $MOLECULE_SCENARIO_DIRECTORY/../default/hosts.yml
      group_vars: $MOLECULE_PROJECT_DIRECTORY/inventory/group_vars
      host_vars: $MOLECULE_PROJECT_DIRECTORY/inventory/host_vars
  playbooks:
    prepare: $MOLECULE_SCENARIO_DIRECTORY/../default/playbooks/${PLAYBOOK:-starter}-init.yml
    converge: $MOLECULE_SCENARIO_DIRECTORY/../default/playbooks/${PLAYBOOK:-starter}-play.yml
    verify: $MOLECULE_SCENARIO_DIRECTORY/../default/playbooks/${PLAYBOOK:-starter}-test.yml
  env:
    ANSIBLE_ROLES_PATH: $MOLECULE_PROJECT_DIRECTORY/roles:$MOLECULE_PROJECT_DIRECTORY/roles-galaxy:$MOLECULE_PROJECT_DIRECTORY/roles-temp
    ANSIBLE_CALLBACK_PLUGINS: $MOLECULE_PROJECT_DIRECTORY/plugins/callback
    ANSIBLE_STRATEGY_PLUGINS: $MOLECULE_PROJECT_DIRECTORY/plugins/strategy/mitogen
  config_options:
    defaults:
      strategy: mitogen_linear
      stdout_callback: unixy2
      verbosity: 1
  lint:
    name: ansible-lint
verifier:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  test_sequence:
    - lint
    - dependency
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - verify
    - destroy
  create_sequence:
    - create
    - prepare
  destroy_sequence:
    - cleanup
    - destroy
  converge_sequence:
    - converge
...
