---
squid_host: "{{ ansible_fqdn }}"
squid_domain: "{{ squid_host }}"

squid_port: 1085
squid_allow_unencrypted: no

squid_ssl_enable: yes
squid_ssl_port: 1443
squid_letsencrypt_cert: example.com

squid_auth_ldap: no
squid_auth_htpasswd: yes
squid_use_squidguard: no
squid_cloaking: true

squid_proxy_users:
  - user: ubuntu1
    pass: supersecret

squid_cachemgr_password: supersecret

squid_local_subnets:
  - 192.168.0.0/16
  - fd00::/64

squid_nopassword_networks:
   - name: internal
     ranges:
      - "192.168.0.0/16"

squid_domain_rules:
  - name: tor
    domain: onion
    host: torify.local
    localhost: yes  # if true, the host will be added to /etc/hosts
    port: 1088

squid_pac:
  pac_types: "{{ squid_pac_types }}"
  direct_nets:
    - "127."
    - "192.168."
  direct_hosts:
    - "localhost"
  direct_domains:
    - ".direct.localdomain"
...
