---
- name: gather facts
  hosts: all
  gather_facts: true
  tags: always

- name: simple proxy services
  hosts: all
  gather_facts: false
  roles:
    - ivansible.lin_tor
    - ivansible.srv_mtproxy
    - ivansible.srv_ziproxy
    - ivansible.srv_dante
  tags: bastion_proxy

- name: services dependent on nginx and tls certificates
  hosts: all
  gather_facts: false
  roles:
    - ivansible.lin_sslh
    - ivansible.lin_nginx
    - ivansible.srv_cdn
    - ivansible.srv_ss
    - ivansible.srv_chisel
    - ivansible.srv_doh
  tags:
    - bastion_tls

- name: squid with tls
  hosts: all
  gather_facts: false
  roles:
    - ivansible.srv_squid
  tags: bastion_squid
...
