---
- name: gather facts
  hosts: all
  gather_facts: true
  strategy: linear  # workaround for mitogen 0.2.9 bug with ansible 2.9.18+ on xenial
  tags: always

- name: simple proxy services
  hosts: all
  gather_facts: false
  roles:
    - ivansible.linux.wireguard
    - ivansible.linux.openvpn
    - ivansible.server.mtproxy
    - ivansible.server.ziproxy
    - ivansible.server.dante
    - ivansible.server.tor
  tags: bastion_proxy

- name: services dependent on nginx and tls certificates
  hosts: all
  gather_facts: false
  roles:
    - ivansible.nginx.sslh
    - ivansible.nginx.nginx
    - ivansible.nginx.cdn
    - ivansible.nginx.ss
    - ivansible.nginx.chisel
    - ivansible.nginx.doh
    - ivansible.nginx.dyndns
    - ivansible.nginx.v2ray
    - ivansible.server.sshtun
  tags:
    - bastion_tls

## squid must go last for the sake of idempotence because
## it enumerates local interfaces created by other roles.
- name: squid with tls
  hosts: all
  gather_facts: false
  roles:
    - ivansible.nginx.squid
  tags: bastion_squid

- name: refresh all facts before forwarding ports
  hosts: all
  gather_facts: true
  strategy: linear  # workaround for mitogen 0.2.9 bug with ansible 2.9.18+ on xenial
  tags: always

- name: setup port forwarding
  hosts:
    - prod_master_all
    - prod_slaves_all
  gather_facts: false
  roles:
    - ivansible.linux.bastion
  tags: bastion_forwards
...
