---
- name: gather facts
  hosts: all
  gather_facts: true
  tags: always

- name: basic linux setup
  hosts: all
  gather_facts: false
  roles:
    - role: ivansible.lin_system
    - role: ivansible.lin_ssh
    - role: ivansible.dev_user
    - role: ivansible.lin_docker
      when: lin_use_docker |bool
  tags: bastion_prepare

- name: simple proxy services
  hosts: all
  gather_facts: false
  roles:
    - ivansible.lin_tor
    - ivansible.srv_mtproxy
    - ivansible.srv_ziproxy
    - ivansible.srv_dante
  tags: bastion_proxy

# Note: please `--skip-tags bastion_cert`
#       when you run this playbook on a single host!
- name: letsencrypt certificates on production master
  hosts: prod_master
  gather_facts: false
  roles:
    - ivansible.cert_cloudflare
  tags:
    - bastion_cert
    - bastion_cert_master

- name: letsencrypt certificates on production slaves
  hosts: prod_slaves
  gather_facts: false
  roles:
    - ivansible.cert_replica
  tags:
    - bastion_cert
    - bastion_cert_slaves

- name: services dependent on nginx and tls certificates
  hosts: all
  gather_facts: false
  roles:
    - ivansible.lin_sslh
    - ivansible.lin_nginx
    - ivansible.srv_ss
    - ivansible.srv_chisel
    - ivansible.srv_doh
  tags:
    - bastion_tls

- name: squid with tls
  hosts: all
  gather_facts: false
  roles:
    - ivansible.srv_squid
  tags: bastion_squid
...
