---
- name: gather facts
  hosts: all
  gather_facts: true
  strategy: linear  # workaround for mitogen 0.2.9 bug with ansible 2.9.18+ on xenial
  tags: always

- name: letsencrypt certificates on production master
  hosts:
    - prod_master_all
  gather_facts: false
  strategy: linear  # mitogen fails when cert_master runs setup for replicas
  roles:
    - ivansible.cert_cloudflare
    - ivansible.cert_master
  tags: cert_master

- name: letsencrypt certificates on development hosts
  hosts:
    - dev_all
    - prod_test
  gather_facts: false
  roles:
    - ivansible.cert_copy
  tags: cert_devel

- name: letsencrypt certificates on production slaves
  hosts:
    - prod_slaves
  gather_facts: false
  roles:
    - ivansible.cert_replica
  tags: cert_slaves
...
