---
- name: gather facts
  hosts: all
  gather_facts: true
  strategy: linear  # workaround for mitogen 0.2.9 bug with ansible 2.9.18+ on xenial
  tags: always

- name: setup docker for development
  hosts: all
  gather_facts: false
  vars:
    docker_extras: true
    docker_bash_completion_extras: true
  roles:
    - role: ivansible.devel.tools
    - role: ivansible.devel.go
    - role: ivansible.linux.docker
      when: lin_use_docker |bool
  tags: devops_docker

- name: deploy ansible playbooks
  hosts: permitted
  gather_facts: false
  vars:
    # avoid task duplication between dev-user and dev-ivantory
    divan_skip_prepare: true
  roles:
    - ivansible.devel.user
    - ivansible.devel.ansible
    # ivantory's ansible playbooks are required by terraform plans
    - ivansible.devel.ivantory
  tags: devops_permitted

- name: configure for devops and cloud control
  hosts: all
  gather_facts: false
  roles:
    - ivansible.devel.hosters
    - ivansible.devel.terraform
    - ivansible.devel.packer
    ## nxserver is required by virtualbox gui (and many others..)
    - role: ivansible.server.nxserver
      when: ansible_architecture == 'x86_64'
    ## mount VM images
    - ivansible.linux.rclone
    - ivansible.devel.vscode
  tags: devops_software

- name: enable host for virtual machines
  hosts: baremetal
  gather_facts: false
  pre_tasks:
    - name: prevent unattanded-upgrades locking dpkg frontend lock
      systemd:
        name: unattended-upgrades
        state: stopped
      become: true
      failed_when: false  # the service may be absent
      no_log: true
      tags: devops_fixes
  roles:
    - ivansible.devel.virtualbox
    - ivansible.devel.vagrant
  tags: devops_virtual

- name: silence cloud-init warning on bender
  hosts: bender
  gather_facts: false
  tasks:
    - name: silence the cloud-init warning
      copy:
        dest: "{{ ansible_user_dir }}/.cloud-warnings.skip"
        content: ""
        mode: 0644
  tags: devops_fixes
...
