---
- name: run the main playbook
  import_playbook: "{{ playbook_dir }}/starter.yml"

- name: deploy ivan's inventory ("ivantory")
  hosts: permitted,!microservers
  gather_facts: false
  vars:
    divan_skip_prepare: true  # already done in dev-user/dev-ansible
  roles:
    - ivansible.devel.ivantory
  tags:
    - ip4only
    - ivantory
...
