---
# usage: ansible-playbook plays-all/lin-refresh.yml -l host1,host2,host3
- name: gather facts
  hosts: all
  gather_facts: true
  tags: always

- hosts: all
  gather_facts: false
  strategy: "{{ linref_play_strategy | default('linear') }}"
  roles:
    - role: ivansible.lin_refresh
...
