---
- name: gather facts
  hosts: all
  gather_facts: true
  strategy: linear  # workaround for mitogen 0.2.9 bug with ansible 2.9.18+ on xenial
  tags: always

- name: databases (master-only)
  hosts:
    - prod_master_all
    - dev_master
  gather_facts: false
  roles:
    - ivansible.server.postgres
    - ivansible.server.mongodb
    - ivansible.server.redis
  tags: master_db

- name: web servers
  hosts: all
  gather_facts: false
  roles:
    - ivansible.nginx.sslh
    - ivansible.nginx.nginx
  tags: master_web

- name: mail (master-only)
  hosts:
    - prod_master_all
    - dev_master
  gather_facts: false
  roles:
    - ivansible.nginx.cgpro
  tags: master_mail

- name: asterisk
  hosts: asterisk_servers
  gather_facts: false
  roles:
    - ivansible.asterisk.core
    - ivansible.asterisk.soho
    - ivansible.asterisk.providers
    - ivansible.asterisk.webui
  tags: master_asterisk

- name: backup
  hosts:
    - prod_all
    - dev_master
  gather_facts: false
  roles:
    - ivansible.linux.rclone
    - ivansible.linux.restic
  tags: master_backup
...
