---
- name: gather facts
  hosts: all
  gather_facts: true
  tags: always

- name: databases (master-only)
  hosts:
    - prod_master_all
    - dev_master
  gather_facts: false
  roles:
    - ivansible.srv_postgres
    - ivansible.srv_mongodb
    - ivansible.srv_redis
  tags: master_db

- name: web servers
  hosts: all
  gather_facts: false
  roles:
    - ivansible.lin_sslh
    - ivansible.lin_nginx
  tags: master_web

- name: mail (master-only)
  hosts:
    - prod_master_all
    - dev_master
  gather_facts: false
  roles:
    - ivansible.srv_cgpro
  tags: master_mail

- name: asterisk
  hosts: asterisk_servers
  gather_facts: false
  roles:
    - ivansible.ast_core
    - ivansible.ast_soho
    - ivansible.ast_providers
    - ivansible.ast_webui
  tags: master_asterisk

- name: backup
  hosts:
    - prod_all
    - dev_master
  gather_facts: false
  roles:
    - ivansible.lin_rclone
    - ivansible.lin_restic
  tags: master_backup
...
