---
- name: gather facts
  hosts: all
  gather_facts: "{{ gather |default(true) |bool }}"
  strategy: linear  # workaround for mitogen 0.2.9 bug with ansible 2.9.18+ on xenial
  tags: always

- hosts: all
  gather_facts: false
  tasks:
  - import_role:
      name: "{{ role }}"
...
