---
- name: gather facts
  hosts: all
  gather_facts: true
  tags: always

- name: setup vagrant boxes
  hosts: vagrant
  gather_facts: false
  tags: starter_prepare
  roles:
    - role: ivansible.vag_share
      when: vag_share_name |default('') != ''  # noqa 602
    - role: ivansible.vag_vbguest

- name: basic linux setup
  hosts: all
  gather_facts: false
  tags: starter_prepare
  roles:
    - role: ivansible.lin_core
    - role: ivansible.lin_ssh
    - role: ivansible.lin_motd
    - role: ivansible.lin_docker
      when: lin_use_docker |bool
  tasks:
    - name: update hostname
      hostname:
        name: "{{ inventory_hostname if starter_hostname in [true, 'true', 'inventory'] else starter_hostname }}"
      become: true
      when: starter_hostname is defined
      tags: starter_hostname

- name: system upgrade
  hosts: all
  gather_facts: false
  tags:
    - starter_prepare
    - refresh
  vars:
    refresh: false
    # time-sync is already done in lin-core
    linref_time_sync: false
  roles:
    - role: ivansible.lin_refresh
      when: refresh |bool

- name: configure main user
  hosts:
    - prod_all
    - permitted
    - vagrant
  gather_facts: false
  tags: starter_user
  roles:
    - ivansible.dev_user

- name: setup ansible
  hosts: permitted
  gather_facts: false
  tags: starter_ansible
  roles:
    - ivansible.dev_ansible
...
