---
- name: gather facts
  hosts: all
  gather_facts: true
  strategy: linear  # workaround for mitogen 0.2.9 bug with ansible 2.9.18+ on xenial
  tags: always

- name: setup vagrant boxes
  hosts: vagrant
  gather_facts: false
  tags: starter_prepare
  roles:
    - role: ivansible.vag_share
      when: vag_share_name |default('',true)
    - role: ivansible.vag_vbguest

- name: update hostname
  hosts: all
  gather_facts: false
  tags: starter_hostname
  vars:
    use_inventory_name: "{{ starter_hostname |default(false,true) |string |lower in 'inventory true yes on 1' }}"
  tasks:
    - name: update hostname
      hostname:
        name: "{{ use_inventory_name |bool |ternary(inventory_hostname, starter_hostname) }}"
      become: true
      when: starter_hostname is defined

- name: prepare core linux
  hosts: all
  gather_facts: false
  tags: starter_prepare
  roles:
    - role: ivansible.lin_core
    - role: ivansible.lin_ssh
    - role: ivansible.lin_motd
    - role: ivansible.lin_rsyslog

- name: configure main user
  hosts:
    - prod_all
    - permitted
    - vagrant
  gather_facts: false
  tags: starter_user
  roles:
    - ivansible.dev_user

- name: setup docker
  hosts: all
  gather_facts: false
  tags: starter_docker
  roles:
    - role: ivansible.lin_docker
      when: lin_use_docker |bool

- name: setup ansible
  hosts: permitted
  gather_facts: false
  tags: starter_ansible
  roles:
    - ivansible.dev_ansible

- name: system upgrade
  hosts: all
  gather_facts: false
  tags: starter_refresh
  vars:
    refresh: false
    # time-sync is already done in lin-core
    linref_time_sync: false
  roles:
    - role: ivansible.lin_refresh
      when: refresh |bool
...
