---
- name: bootstrap termux python
  hosts: termux
  strategy: linear
  gather_facts: false
  tags: termux_bootstrap
  roles:
    - ivansible.termux_bootstrap

- name: setup termux core and boostrap proot
  hosts: termux
  gather_facts: false
  tags: termux_core
  roles:
    - ivansible.termux_core

- name: gather facts about ubuntu in termux
  hosts: termuntu
  gather_facts: true
  strategy: linear  # workaround for mitogen 0.2.9 bug with ansible 2.9.18+ on xenial
  tags: always

- name: setup ubuntu in termux
  hosts: termuntu
  gather_facts: false
  tags: termux_ubuntu_setup
  roles:
    - ivansible.termux_ubuntu
    - ivansible.lin_motd
    - ivansible.dev_user
...
