---
- name: gather facts
  hosts: all,!keenetic_ndm,!keenetic_cli
  gather_facts: true
  strategy: linear  # workaround for mitogen 0.2.9 bug with ansible 2.9.18+ on xenial
  tags: always

- name: linux networking
  hosts:
    - net_linux
    - net_test
  gather_facts: false
  roles:
    - ivansible.linux.net
  tags:
    - vpn_linux
    - vpn_linux_net

- name: wireguard linux peers
  hosts: wireguard_peers
  gather_facts: false
  roles:
    - ivansible.linux.wireguard
  tags:
    - vpn_linux
    - vpn_wireguard
    - vpn_wg

- name: sshtun servers
  hosts: sshtun_servers
  gather_facts: false
  roles:
    - ivansible.server.sshtun
  tags:
    - vpn_linux
    - vpn_sshtun

- name: yggdrasil linux peers
  hosts: yggdrasil_linux
  gather_facts: false
  roles:
    - ivansible.linux.yggdrasil
  tags:
    - vpn_linux
    - vpn_yggdrasil

- name: dynamic keepalived routing
  hosts: net_vrrp
  gather_facts: false
  roles:
    - ivansible.linux.keepalived
  tags:
    - vpn_linux
    - vpn_keepalived
    - vpn_vrrp

- name: keenetic entware vpn
  hosts: keenetic_wrt
  gather_facts: false
  roles:
    - ivansible.entware.net
    - ivansible.entware.v2ray
    - ivansible.entware.sshtun
    - ivansible.entware.openvpn
    - ivansible.entware.wireguard
    - ivansible.entware.yggdrasil
  tags:
    - vpn_keenetic
    - vpn_wrt

- name: keenetic ndms vpn
  hosts: keenetic_ndm
  strategy: linear  # mitogen breaks httpapi
  gather_facts: false
  roles:
    - ivansible.ndms.firewall
    - ivansible.ndms.wireguard
    - ivansible.ndms.openvpn
  tags:
    - vpn_keenetic
    - vpn_ndm

- name: openvpn servers
  ## this play is last because it's long
  hosts: openvpn_servers
  gather_facts: false
  roles:
    - ivansible.linux.openvpn
  tags:
    - vpn_openvpn
    - vpn_ovpn
    - vpn_long
...
