---
name: Molecule test
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:

env:
  ANSIBLE_FORCE_COLOR: true

jobs:
  local_test:
    name: host
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-16.04
          - ubuntu-18.04
        playbook:
          # notes:
          #   * bastion is flagged - testing isolated in docker
          #   * master is flagged - testing isolated in docker
          #   * starter mainly duplicates ivantory - disabled
          # - bastion
          # - master
          - devops
          - ivantory
          # - starter
    env:
      IVATEST_FIREWALL: ferm
      IVATEST_SSH_SERVER: false
      IVATEST_SYSTEMD_TMPFILES: false  # systemd-tmpfiles fails on github runner
      TARGET: local
      PLAYBOOK: ${{ matrix.playbook }}

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Workaround for github issue with heroku gpg key
        run: curl -L https://cli-assets.heroku.com/apt/release.key | sudo apt-key add -
        if: matrix.os == 'ubuntu-16.04'

      - name: Install requisites
        shell: bash
        run: |
          # stock and pypy flavors of PyYAML are incompatible:
          sudo apt-get remove -q -y python3-yaml
          sudo -H pip3 install -U pip setuptools wheel
          # also pulled: ansible-lint yamllint flake8
          sudo -H pip3 install docker jmespath boto3 mitogen molecule pytest testinfra
          # fix mitogen strategy symlink
          ln -sf $(python3 -c "import ansible_mitogen; print(ansible_mitogen.__path__[0])")/plugins/strategy ./plugins/strategy/mitogen

      - name: Run test
        shell: bash
        run: |
          molecule test -s $TARGET

  docker_test:
    name: docker
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        playbook:
          # notes:
          #   * bastion is flagged - testing isolated in docker
          #   * master is flagged - testing isolated in docker
          - bastion
          - master
          # - devops
          # - ivantory
          # - starter
        target:
          - all
    env:
      IVATEST_FIREWALL: none
      IVATEST_SSH_SERVER: true
      IVATEST_SYSTEMD_TMPFILES: true
      TARGET: ${{ matrix.target }}
      PLAYBOOK: ${{ matrix.playbook }}

    steps:  # copy-pasting above steps since anchors are unsupported
      - name: Checkout
        uses: actions/checkout@master

      - name: Install requisites
        shell: bash
        run: |
          # stock and pypy flavors of PyYAML are incompatible:
          sudo apt-get remove -q -y python3-yaml
          sudo -H pip3 install -U pip setuptools wheel
          # also pulled: ansible-lint yamllint flake8
          sudo -H pip3 install docker jmespath boto3 mitogen molecule pytest testinfra
          # fix mitogen strategy symlink
          ln -sf $(python3 -c "import ansible_mitogen; print(ansible_mitogen.__path__[0])")/plugins/strategy ./plugins/strategy/mitogen

      - name: Run test
        shell: bash
        run: |
          molecule test -s $TARGET

  plugins_test:
    name: plugins
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - plugins
    env:
      TARGET: ${{ matrix.target }}

    steps:  # copy-pasting above steps since anchors are unsupported
      - name: Checkout
        uses: actions/checkout@master

      - name: Install requisites
        shell: bash
        run: |
          # stock and pypy flavors of PyYAML are incompatible:
          sudo apt-get remove -q -y python3-yaml
          sudo -H pip3 install -U pip setuptools wheel
          # also pulled: ansible-lint yamllint flake8
          sudo -H pip3 install docker jmespath boto3 mitogen molecule pytest testinfra
          # fix mitogen strategy symlink
          ln -sf $(python3 -c "import ansible_mitogen; print(ansible_mitogen.__path__[0])")/plugins/strategy ./plugins/strategy/mitogen
          # fix symlink for a role with custom modules
          ln -sf ~/.cache/molecule/ivantory-test/$TARGET/roles ./roles-galaxy

      - name: Run test
        shell: bash
        run: |
          molecule test -s $TARGET
...
