---
name: test

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: '15 2 * * 1'
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

jobs:
  test:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    env:
      SCENARIO: ${{ matrix.scenario }}
      PLAYBOOK: ${{ matrix.playbook }}
      ANSIBLE_FORCE_COLOR: true

      IVATEST_FIREWALL: 'none'
      IVATEST_SSH_SERVER: true
      IVATEST_SYSTEMD_TMPFILES: true
      ## mitigate mitogen detecting python as python2 on focal
      IVATEST_PYTHON_GROUP: python3

      ## environment for local host:
      # IVATEST_SSH_SERVER: false
      # IVATEST_SYSTEMD_TMPFILES: false

    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        include:
          - name: ivantory-docker
            playbook: ivantory
            os: ubuntu-latest
            scenario: default

          - name: devel-docker
            playbook: devel
            os: ubuntu-latest
            scenario: default

          - name: bastion-docker
            playbook: bastion
            os: ubuntu-latest
            scenario: default

          - name: master-docker
            playbook: master
            os: ubuntu-latest
            scenario: default

          - name: plugins
            playbook: none
            os: ubuntu-latest
            scenario: plugins

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: install requisites
        run: |
          sudo apt-get remove -qy python3-yaml
          sudo rm -f /opt/pipx_bin/ansible*
          sudo -H python3 -m pip install -U pip setuptools wheel
          sudo -H pip3 install -r ./requirements.txt

      - name: fix mitogen and molecule
        run: |
          MITOGEN=$(python3 -c "import ansible_mitogen as m; print(m.__path__[0])")
          VENV=$(dirname $MITOGEN)
          PRJ=$(pwd)
          SRC=$PRJ/.github/workflows
          sudo patch -d $VENV/molecule_docker -p1 -i $SRC/docker-mitogen.patch
          sudo patch -d $VENV/mitogen -p1 -i $SRC/mitogen-distro.patch
          ## make mitogen strategy symlink
          ln -sf $MITOGEN/plugins/strategy $PRJ/plugins/strategy/mitogen

      - name: make symlink for custom modules
        if: ${{ matrix.scenario == 'plugins' }}
        run: |
          ln -sf ~/.cache/molecule/ivantory-test/$SCENARIO/roles ./roles-galaxy

      - name: install required collections
        run: |
          rm -f collections/ansible_collections
          mkdir -p collections/ansible-collections
          ./bin/import-roles

      - name: run test
        run: |
          molecule test -s $SCENARIO
...
