---
name: test

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: '15 2 * * 1'
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

jobs:
  test:
    name: ${{ matrix.name }}
    runs-on: ubuntu-20.04
    env:
      SCENARIO: ${{ matrix.scenario }}
      PLAYBOOK: ${{ matrix.playbook }}
      ANSIBLE_FORCE_COLOR: true
      PY_COLORS: true

    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        include:
          - name: ivantory
            playbook: ivantory

          - name: devel
            playbook: devel

          - name: bastion
            playbook: bastion

          - name: master
            playbook: master

          - name: plugins
            scenario: plugins

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: install requisites
        run: |
          sudo apt-get remove -qy python3-yaml
          sudo rm -f /opt/pipx_bin/ansible*
          sudo -H python3 -m pip install -U pip setuptools wheel
          sudo -H pip3 install -r ./requirements.txt

      - name: fix mitogen and molecule
        run: |
          MITOGEN=$(python3 -c "import ansible_mitogen as m; print(m.__path__[0])")
          VENV=$(dirname $MITOGEN)
          PRJ=$(pwd)
          SRC=$PRJ/.github/workflows
          sudo patch -d $VENV/molecule_docker -p1 -i $SRC/docker-mitogen.patch
          sudo patch -d $VENV/mitogen -p1 -i $SRC/mitogen-distro.patch
          ln -sf $MITOGEN/plugins/strategy $PRJ/plugins/strategy/mitogen

      - name: run test
        run: |
          mkdir -p $(realpath ./collections/ansible_collections)
          molecule dependency -s ${SCENARIO:-default}
          molecule test -s ${SCENARIO:-default}
...
